<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>_8.Ariketa.IgorGarcia</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Page Remove="AssemblyInfo.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="AssemblyInfo.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Compile>
  </ItemGroup>

</Project>
